scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile38`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level6isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile121`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level12isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile45`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level7isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile60`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level9isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile13`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level3isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile117`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Secret`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile85`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level12isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile20`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level4isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile93`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level13isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile101`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level14isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level2isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile109`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level15isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile116`, function (sprite, location) {
    game.gameOver(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile78`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level11isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile51`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level8isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile69`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level10isreal`)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile28`, function (sprite, location) {
    mySprite.setPosition(128, 128)
    tiles.setCurrentTilemap(tilemap`Level5isreal`)
})
let mySprite: Sprite = null
scene.setBackgroundImage(assets.image`myImage0`)
game.setDialogTextColor(14)
game.showLongText("\"Click Space To Start\"", DialogLayout.Bottom)
scene.setBackgroundImage(img`
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    `)
mySprite = sprites.create(img`
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    .................................................
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`Level10isreal`)
mySprite.setPosition(128, 128)
controller.moveSprite(mySprite, 100, 100)
scene.cameraFollowSprite(mySprite)
info.startCountdown(300)
Render.setViewMode(ViewMode.raycastingView)
music.play(music.createSong(hex`0078000408020100001c00010a006400f4016400000400000000000000000000000000050000046200000004000222290400080002202a08000c0001240c001000021e251000140002202914001800031e242918001c0001241c0020000320242920002400021d292400280002202728002c0002222a2c003000021d2730003400021b273400380002222a`), music.PlaybackMode.LoopingInBackground)
music.play(music.stringPlayable("C5 B A G F E D C ", 200), music.PlaybackMode.LoopingInBackground)
music.play(music.stringPlayable("C5 B C5 B C5 B C5 B ", 100), music.PlaybackMode.LoopingInBackground)
music.play(music.stringPlayable("D E D E D E D E ", 100), music.PlaybackMode.LoopingInBackground)
music.play(music.stringPlayable("C C C C C C C C ", 100), music.PlaybackMode.LoopingInBackground)
